### ISSUE TITLE
Investigate running tests via docker:dind-rootless

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#190] opened 2020-12-10 16:02 UTC
As an additional container rather then using full fledged Docker Builder VM

Related guide: https://cirrus-ci.org/guide/docker-builds-on-kubernetes/?h=+docker

**Comment by edigaryev** [comment] 2020-12-10 19:15
The preliminary results are that it's not possible to run rootless in Docker without a `--privileged` flag (or without enabling certain capabilities and disabling security confinements):

```
% docker run -it --rm docker:dind-rootless | tail -n 1
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted
```

Related RootlessKit issues:

* https://github.com/rootless-containers/rootlesskit/issues/172
* https://github.com/rootless-containers/rootlesskit/issues/68

In the Docker's rootless guide the `docker:dind-rootless` is also started with the `--privileged` flag, see https://docs.docker.com/engine/security/rootless/#rootless-docker-in-docker.

**Comment by edigaryev** [comment] 2020-12-10 20:28
> The preliminary results are that it's not possible to run rootless in Docker without a `--privileged` flag (or without enabling certain capabilities and disabling security confinements)

This seems to be freshly confirmed by the Podman project too: https://github.com/containers/podman/issues/4131#issuecomment-740189121.

**Comment by edigaryev** [comment] 2020-12-21 20:44
I'm going to close this one for now because there's no straightforward way ATM to do this without turning off Docker's security features.

**Closed by edigaryev** 2020-12-21 20:44 UTC
Labels: enhancement
