### ISSUE TITLE
Investigate memory usage of `cache` instructions.

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#799] opened 2024-10-08 14:34 UTC
There are reports that a cache entry of `1003Mb` consumes more than `2GB` of memory which gets k8s pods to get `OOMKilled`.

**Comment by edigaryev** [comment] 2024-10-24 16:39
Closing because of improbable reproducibility, please reopen if new details will arise.

Previous issues and PRs, for reference:

* https://github.com/cirruslabs/cirrus-ci-agent/issues/346
* https://github.com/cirruslabs/cirrus-ci-agent/pull/347

**Closed by edigaryev** 2024-10-24 16:39 UTC
Labels: enhancement
