### ISSUE TITLE
task script "fails" even though it had exit code 0?

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-cli#124] opened 2020-10-10 23:45 UTC
When running cirrus run --verbose --dirty lint[1] in a fresh clone of https://github.com/awooos/flail on my system, it says `container exited with <nil> error and exit code 0`, then tells me it failed.

I suspect having logs from the actual running commands would help, but I'm not sure if/how I can get those.

```
~/dev/os/awooos/flail$ cirrus run --verbose --dirty lint
🕙 'Lint' Task 02:45
   ✅ Preparing execution environment... 3.8s
   ✅ docker pull 6.5s
   ✅ 'install' script 02:27
   ❌ 'main' script 1.0s
      begin streaming logs
      command failed

   creating Docker client
   creating container using working volume cirrus-working-volume-9ca71a13-5127-4bd1-bc50-ed060f8b3519
   starting container 0b05f1ae00845dc2b8012cff07494d31a01f4929380f6d98f87bec0b7b2e8635
   received heartbeat
   agent signal: urgent I/O condition
   received heartbeat
   waiting for container 0b05f1ae00845dc2b8012cff07494d31a01f4929380f6d98f87bec0b7b2e8635 to finish
   received heartbeat
   received heartbeat
   container exited with <nil> error and exit code 0
   cleaning up container 0b05f1ae00845dc2b8012cff07494d31a01f4929380f6d98f87bec0b7b2e8635

Error: build failed: task Lint (0) failed
2020/10/10 19:38:27 build failed: task Lint (0) failed
~/dev/os/awooos/flail$
```

**Comment by duckinator** [comment] 2020-10-10 23:53
I just noticed that it didn't clean up one of the containers it used, and looked into that a bit.

It appears to be a file permission problem. I do know that on Fedora, you frequently have to use the `:z` for volume bind mounts (see https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label ). That might be related?

```
$ docker ps -a
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS                      PORTS               NAMES
816d478bcad2        gcr.io/cirrus-ci-community/cirrus-ci-agent:v1.8.0   "/bin/sh -c 'cp /bin…"   5 minutes ago       Exited (23) 5 minutes ago                       reverent_mcclintock
$ docker logs 816d478bcad2
rsync: opendir "/project-dir/." failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
$
```

<details>
<summary>Output of <code>docker inspect</code></summary>

```
[
    {
        "Id": "816d478bcad21ecd5b4eecc8266b2879f25c148efd38f5decc311260fe3f66d1",
        "Created": "2020-10-10T23:41:16.07612393Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "cp /bin/cirrus-ci-agent /tmp/cirrus-ci/cirrus-ci-agent && rsync -r --filter=':- .gitignore' /project-dir/ /tmp/cirrus-ci/working-dir"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 23,
            "Error": "",
            "StartedAt": "2020-10-10T23:41:17.52460292Z",
            "FinishedAt": "2020-10-10T23:41:17.639903165Z"
        },
        "Image": "sha256:4066a277c6bfb65ba7f72bede96264571f62d32a11baf862de90880e4f2c9e17",
        "ResolvConfPath": "/var/lib/docker/containers/816d478bcad21ecd5b4eecc8266b2879f25c148efd38f5decc311260fe3f66d1/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/816d478bcad21ecd5b4eecc8266b2879f25c148efd38f5decc311260fe3f66d1/hostname",
        "HostsPath": "/var/lib/docker/containers/816d478bcad21ecd5b4eecc8266b2879f25c148efd38f5decc311260fe3f66d1/hosts",
        "LogPath": "",
        "Name": "/reverent_mcclintock",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "system_u:object_r:container_file_t:s0:c526,c660",
        "ProcessLabel": "system_u:system_r:container_t:s0:c526,c660",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "journald",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": [
                {
                    "Name": "nofile",
                    "Hard": 1024,
                    "Soft": 1024
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "cirrus-working-volume-87589128-8142-48a0-9ba2-0350fe0cd11f",
                    "Target": "/tmp/cirrus-ci"
                },
                {
                    "Type": "bind",
                    "Source": "/home/puppy/dev/os/awooos/flail",
                    "Target": "/project-dir",
                    "ReadOnly": true
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/38b13756a312e6ac0b14898e2fd7fe7f3c7b1b239924043596cef1050cba0cef-init/diff:/var/lib/docker/overlay2/35dc0d0c182e9068d9e766b0d2af8277a63f5215b73bde2851d664e140620a92/diff:/var/lib/docker/overlay2/f0c2912f87312d0fb179b45b195655c90bd22d197453820991cf50859c9775ee/diff:/var/lib/docker/overlay2/5d9f3f94924ed5b82d8f4f56f9a6585fc01f4a5d55861f9de085ceb91c3f95ee/diff",
                "MergedDir": "/var/lib/docker/overlay2/38b13756a312e6ac0b14898e2fd7fe7f3c7b1b239924043596cef1050cba0cef/merged",
                "UpperDir": "/var/lib/docker/overlay2/38b13756a312e6ac0b14898e2fd7fe7f3c7b1b239924043596cef1050cba0cef/diff",
                "WorkDir": "/var/lib/docker/overlay2/38b13756a312e6ac0b14898e2fd7fe7f3c7b1b239924043596cef1050cba0cef/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "cirrus-working-volume-87589128-8142-48a0-9ba2-0350fe0cd11f",
                "Source": "/var/lib/docker/volumes/cirrus-working-volume-87589128-8142-48a0-9ba2-0350fe0cd11f/_data",
                "Destination": "/tmp/cirrus-ci",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/home/puppy/dev/os/awooos/flail",
                "Destination": "/project-dir",
                "Mode": "",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "816d478bcad2",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "cp /bin/cirrus-ci-agent /tmp/cirrus-ci/cirrus-ci-agent && rsync -r --filter=':- .gitignore' /project-dir/ /tmp/cirrus-ci/working-dir"
            ],
            "Image": "gcr.io/cirrus-ci-community/cirrus-ci-agent:v1.8.0",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b2583426cb6da1f917bb773e93fcb1bea9a046c225b50164fca45af97e55d30b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/b2583426cb6d",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "ff27aac6749727bb7735ff6b2373b22791f8e0f2584c91bb14ff37d63d07a30d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

</details>

**Comment by edigaryev** [comment] 2020-10-12 19:26
Hi! Thanks for the report and a thoughtful investigation!

I was able to reproduce your issue with Docker daemon started with `--selinux-enabled` flag (or almost the same thing in `/etc/docker/daemon.json`).

However, even through that relabelling feature of Docker you've mentioned would work, I'm not sure if it would be a good fit for everyone, because it actually modifies the labels of all the files that are mounted, which may lead to some unexpected results like in https://github.com/moby/moby/issues/30934.

There's however a [`--security-opt="label=disabled"`](https://docs.docker.com/engine/reference/run/#security-configuration) option for the `docker run` that doesn't modify the labels, yet simply disables the label checking. Assuming that you're actually running Docker with `--selinux-enabled` intentionally, would that still work for you security-wise?

**Comment by duckinator** [comment] 2020-10-12 21:04
@edigaryev I'm using Fedora 31's `moby-engine` package with the default configuration; `--selinux-enabled` comes from the `/etc/sysconfig/docker` file installed by the `moby-engine` package.

That file appears to be Fedora-specific, and the source for it can be found here: <https://src.fedoraproject.org/rpms/moby-engine/blob/master/f/docker.sysconfig>.

I'm personally okay with that option being used, although I don't know how others would feel. :woman_shrugging: 


... I also just discovered that the Docker folks apparently maintain their own separate repo for Fedora, for some reason, and the source used to generate the RPM isn't available. So I can't easily confirm if they do the same thing as Fedora's moby-engine package. :upside_down_face:

**Comment by edigaryev** [comment] 2020-10-13 15:37
> EDITED: it's not yet fixed. 😅

Indeed: as I began testing the fix on CentOS and Fedora, it turned out that the Netfilter rules on these distributions are more strict (particularly the `INPUT` chain in the filter table), which results in the [cirrus-ci-agent](https://github.com/cirruslabs/cirrus-ci-agent) not being able to communicate with the CLI.

However, we have an idea how to fix this (see https://github.com/cirruslabs/cirrus-cli/pull/120#issuecomment-704848472) 👌

**Comment by edigaryev** [comment] 2020-10-14 12:52
Just shipped the [0.13.0 release](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.13.0) and it seems to be working fine with `--selinux-enabled` Docker daemon on CentOS 7 and Fedora 31.

@duckinator can you check if it works for you too?

**Comment by fkorotkov** [comment] 2020-11-02 13:09
Closing for now. @duckinator please reopen if the issue still persists.

**Closed by fkorotkov** 2020-11-02 13:09 UTC

**Comment by duckinator** [comment] 2020-11-09 06:13
Sorry for the slow response, this got buried in a deluge of notifications. :sweat_smile: 

I can confirm that it works, using v0.14.0-bdff1c5.
