### ISSUE TITLE
 v0.43.0  no longer working

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-cli#349] opened 2021-03-26 06:48 UTC
v0.42.8 was working fine, but v0.43.0 doesn't. This is the output:

```
INFO[0000] worker successfully registered               
INFO[0010] started task 5794341756076032                
ERRO[0010] failed to run task 5794341756076032: exit status 2 
ERRO[0010] failed to notify the server about the failed task 5794341756076032: rpc error: code = Unimplemented desc = Method org.cirruslabs.ci.services.cirruscigrpc.CirrusWorkersService/TaskFailed is unimplemented 
INFO[0030] task 5794341756076032 completed
```

Let me know if you need any other info.

**Comment by fkorotkov** [comment] 2021-03-26 12:10
Should be fixed now. Sorry for the inconvenience. The root cause will be fixed in #350 from happening again.

**Closed by fkorotkov** 2021-03-26 12:10 UTC
